service: lingerstudio-nft-data
plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2

functions:
  metadata:
    handler: src/index.metadata
    events:
      - http:
          path: metadata
          method: post