service: lingerstudio-nft-data
plugins:
  - serverless-plugin-typescript
  - serverless-offline
provider:
  name: aws
  stage: production
  runtime: nodejs14.x
  region: ap-northeast-2
  tags:
    Application: lingerstudio

functions:
  metadata:
    handler: src/index.metadata
    events:
      - http:
          path: metadata
          method: post
          private: true
  deposit:
    handler: src/deposit.deposit
    events:
      - http:
          path: deposit
          method: post
          private: false
    environment:
      LINGER_WALLET_PUBLICKEY: "LinfnYDjPQM1HuRfNgErh5VCiU7NVP5Yyf9Bbo1EtwY"
      OPERATOR_ACCOUNT: "NW3R8SIGlPbBTB2ALu7bdgobWKiE6FqGpKnSG4xu4vIFDUhSrjqdVbVPFw3NNrxyU/prFyhC3K0VibrlQ6mTcg=="
