service: lingerstudio-nft-data
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  stage: dev
  runtime: nodejs14.x
  region: ap-northeast-2
  tags:
    Application: lingerstudio

functions:
  metadata:
    handler: src/metadata.handler
    events:
      - http:
          path: metadata
          method: post
          private: false
  deposit:
    handler: src/deposit.handler
    events:
      - http:
          path: deposit
          method: post
          private: false
    timeout: 30
