service: lingerstudio-nft-data
plugins:
  - serverless-plugin-typescript
  - serverless-offline
provider:
  name: aws
  stage: production
  runtime: nodejs14.x
  region: ap-northeast-2
  tags:
    Application: lingerstudio

functions:
  metadata:
    handler: src/index.metadata
    events:
      - http:
          path: metadata
          method: post
          private: true
  deposit:
    handler: src/deposit.deposit
    events:
      - http:
          path: deposit
          method: post
          private: false
    environment:
      OPERATOR_ACCOUNT: "[53,109,209,241,34,6,148,246,193,76,29,128,46,238,219,118,10,27,88,168,132,232,90,134,164,169,210,27,140,110,226,242,5,13,72,82,174,58,157,85,181,79,23,13,205,54,188,114,83,250,107,23,40,66,220,173,21,137,186,229,67,169,147,114]"
